export const routeEffects = {
    "bleed": "assets/effect-img/bleed.png",
    "blight": "assets/effect-img/blight.png",
    "buff": "assets/effect-img/buff.png",
    "debuff": "assets/effect-img/debuff.png",
    "disease": "assets/effect-img/disease.png",
    "gold": "assets/effect-img/loot.png",
    "heal stress": "assets/effect-img/heal_stress.png",
    "heal": "assets/effect-img/heal.png",
    "loot": "assets/effect-img/loot.png",
    "none": "assets/effect-img/none.png",
    "poison": "assets/effect-img/poison.png",
    "purge negative quirk": "assets/effect-img/purge_negative_quirk.png",
    "purge positive quirk": "assets/effect-img/purge_positive_quirk.png",
    "quirk negative": "assets/effect-img/quirk_negative.png",
    "quirk positive": "assets/effect-img/quirk_positive.png",
    "stress": "assets/effect-img/stress.png",
    "summon": "assets/effect-img/summon.png",
    "torch": "assets/effect-img/torch.png",
}